format_version: 9
environments:
  dev:
    pipelines:
      - build

pipelines:
  build:
    group: firstGroup
    materials:
      gocd-playgroud: # this is the name of material
        git: https://github.com/thekneeslim/gocd-playground.git
    stages:
      - build: # name of stage
          jobs:
            job-name: # name of the job
              elastic_profile_id: demo-app
              tasks:
                - exec:
                    command: bash
                    arguments:
                    - echo "hello world"