format_version: 9
environments:
  dev:
    pipelines:
      - first_pipeline
      - second_pipeline

pipelines:
  first_pipeline:
    group: firstGroup
    materials:
      gocd-playgroud: # this is the name of material
        git: https://github.com/thekneeslim/gocd-playground.git
    stages:
      - first: # name of stage
          jobs:
            job-name: # name of the job
              elastic_profile_id: demo-app
              tasks:
                - exec:
                    command: echo
                    arguments:
                    - "hello world"
              artifacts:
                - build:
                    source: "*"
                    destination: my_artifact_destination
      - second:
          jobs:
            get-artifact:
              elastic_profile_id: demo-app
              tasks:
                  - exec:
                      command: ls
                  - fetch:
                      pipeline: first_pipeline
                      stage: first
                      job: job-name
                      source: my_artifact_destination
                      destination: copied-configuration/
  second_pipeline:
    group: firstGroup
    materials:
      myUpStream:
        pipeline: first_pipeline
        stage: second
    stages:
      - demo-dependency:
          jobs:
            demo-dependency:
              elastic_profile_id: demo-app
              tasks:
                - fetch:
                    pipeline: first_pipeline
                    stage: first
                    job: job-name
                    source: my_artifact_destination
                    destination: copied-configuration-from-previous-pipeline/
                - exec:
                  command: ls
                  argument:
                    - copied-configuration-from-previous-pipeline
