format_version: 9

pipelines:
  new_source_pipeline:
    group: firstGroup
    materials:
      gocd-playgroud: # this is the name of material
        git: https://github.com/thekneeslim/gocd-playground.git
    stages:
      - new_source_first_stage: # name of stage
          jobs:
            new_source_job: # name of the job
              elastic_profile_id: demo-app
              tasks:
                - exec:
                    command: echo
                    arguments:
                      - "hello world"
              artifacts:
                - build:
                    source: "*"
                    destination: my_artifact_destination
                - build:
                    source: new_source.txt
                    destination: file_from_new_source.txt