format_version: 9

pipelines:
  second_pipeline:
    group: firstGroup
    materials:
      myUpStream:
        pipeline: first_pipeline
        stage: first_pipeline_stage_one
    stages:
      - second_pipeline_stage_one:
          jobs:
            demo-second_pipeline_job_one:
              elastic_profile_id: demo-app
              tasks:
                - fetch:
                    pipeline: first_pipeline
                    stage: first_pipeline_stage_one
                    job: first_pipeline_job_one
                    source: my_artifact_destination
                    destination: copied-configuration-from-previous-pipeline/
                - fetch:
                    pipeline: first_pipeline
                    stage: first_pipeline_stage_one
                    job: first_pipeline_job_one
                    source: file.md
                    destination: file.md
                - exec:
                    command: ls
