format_version: 9

pipelines:
  fan_out_pipeline_one:
    group: firstGroup
    materials:
      fan_in:
        pipeline: fan_in_pipeline
        stage: fan_in_stage
    stages:
      - fan_out_one_stage:
          jobs:
            list_all_artifacts:
              elastic_profile_id: demo-app
              tasks:
                - fetch:
                    pipeline: first_pipeline/second_pipeline/fan_in_pipeline
                    stage: first_pipeline_stage_one
                    job: first_pipeline_job_one
                    source: file.md
                    destination: fan_in_file.md
                - exec:
                    command: ls
